

name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3



      - name: Set up SSH key
        run:
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2__SSH_KEY}}" > ~/.ssh/ec2_key.pem
            chmod 600 ~/.ssh/ec2_key.pem

    


      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ubuntu@${{ secrets.EC2__PUBLIC_IP}} << 'EOF'
            cd /home/ubuntu/Desktop/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi
          EOF
          