name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key to agent
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }} 

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=yes ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -e  # Exit on error
            cd /home/ubuntu/Desktop/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
          EOF